// Generated by Hebron at 4/3/2022 2:10:11 AM

using System;
using System.Runtime.InteropServices;
using Hebron.Runtime;

namespace SqliteSharp
{
	unsafe partial class Sqlite
	{
		public static uint countLookasideSlots(LookasideSlot* p)
		{
			uint cnt = (uint)(0);
			while ((p) != null)
			{
				p = p->pNext;
				cnt++;
			}

			return (uint)(cnt);
		}
	}
}