// Generated by Hebron at 4/3/2022 2:10:11 AM

using System;
using System.Runtime.InteropServices;
using Hebron.Runtime;

namespace SqliteSharp
{
	unsafe partial class Sqlite
	{
		public static Index indexIteratorFirst(IndexIterator* pIter, int* pIx)
		{
			if ((pIter->eType) != 0)
			{
				*pIx = (int)(pIter->u.ax.aIdx[0].ix);
				return pIter->u.ax.aIdx[0].p;
			}
			else
			{
				*pIx = (int)(0);
				return pIter->u.lx.pIdx;
			}
		}
		public static Index indexIteratorNext(IndexIterator* pIter, int* pIx)
		{
			if ((pIter->eType) != 0)
			{
				int i = (int)(++pIter->i);
				if ((i) >= (pIter->u.ax.nIdx))
				{
					*pIx = (int)(i);
					return null;
				}

				*pIx = (int)(pIter->u.ax.aIdx[i].ix);
				return pIter->u.ax.aIdx[i].p;
			}
			else
			{
				++(*pIx);
				pIter->u.lx.pIdx = pIter->u.lx.pIdx.pNext;
				return pIter->u.lx.pIdx;
			}
		}
	}
}