// Generated by Hebron at 4/3/2022 2:10:11 AM

using System;
using System.Runtime.InteropServices;
using Hebron.Runtime;

namespace SqliteSharp
{
	unsafe partial class Sqlite
	{
		public static void yy_accept(yyParser yypParser)
		{
			Parse pParse = yypParser.pParse;
			yypParser.pParse = pParse;
		}
		public static void yy_destructor(yyParser yypParser, ushort yymajor, YYMINORTYPE* yypminor)
		{
			Parse pParse = yypParser.pParse;
			switch (yymajor)
			{
				case 204:
				case 239:
				case 240:
				case 252:
					{
						sqlite3SelectDelete(pParse.db, (yypminor->yy47));
					}

					break;
				case 216:
				case 217:
				case 246:
				case 248:
				case 260:
				case 267:
				case 278:
				case 280:
				case 283:
				case 290:
				case 295:
				case 311:
					{
						sqlite3ExprDelete(pParse.db, (yypminor->yy528));
					}

					break;
				case 221:
				case 231:
				case 232:
				case 244:
				case 247:
				case 249:
				case 253:
				case 254:
				case 262:
				case 268:
				case 277:
				case 279:
				case 310:
					{
						sqlite3ExprListDelete(pParse.db, (yypminor->yy322));
					}

					break;
				case 238:
				case 245:
				case 256:
				case 257:
				case 263:
					{
						sqlite3SrcListDelete(pParse.db, (yypminor->yy131));
					}

					break;
				case 241:
					{
						sqlite3WithDelete(pParse.db, (yypminor->yy521));
					}

					break;
				case 251:
				case 306:
					{
						sqlite3WindowListDelete(pParse.db, (yypminor->yy41));
					}

					break;
				case 261:
				case 264:
				case 270:
					{
						sqlite3IdListDelete(pParse.db, (yypminor->yy254));
					}

					break;
				case 273:
				case 307:
				case 308:
				case 309:
				case 312:
					{
						sqlite3WindowDelete(pParse.db, (yypminor->yy41));
					}

					break;
				case 286:
				case 291:
					{
						sqlite3DeleteTriggerStep(pParse.db, (yypminor->yy33));
					}

					break;
				case 288:
					{
						sqlite3IdListDelete(pParse.db, (yypminor->yy180).b);
					}

					break;
				case 314:
				case 315:
				case 316:
					{
						sqlite3ExprDelete(pParse.db, (yypminor->yy595).pExpr);
					}

					break;
				default:
					break;
			}
		}
		public static void yy_pop_parser_stack(yyParser pParser)
		{
			yyStackEntry* yytos;
			yytos = pParser.yytos--;
			yy_destructor(pParser, (ushort)(yytos->major), &yytos->minor);
		}
		public static ushort yy_reduce(yyParser yypParser, uint yyruleno, int yyLookahead, Token yyLookaheadToken, Parse pParse)
		{
			int yygoto = 0;
			ushort yyact = 0;
			yyStackEntry* yymsp;
			int yysize = 0;
			(void)(yyLookahead);
			(void)(yyLookaheadToken);
			yymsp = yypParser.yytos;
			switch (yyruleno)
			{

	 YYMINORTYPE yylhsminor = new YYMINORTYPE();  case  0 :  { pParse.explain = (byte)(1); }
			break;  case  1 :  { pParse.explain = (byte)(2); }
			break;  case  2 :  { sqlite3FinishCoding(pParse); }
			break;  case  3 :  { sqlite3BeginTransaction(pParse, (int)(yymsp[-1].minor.yy394)); }
			break;  case  4 :  { yymsp[1].minor.yy394 = (int)(7); }
			break;  case  5 :  case  6 :  ;  case  7 :  ;  case  321 :  ;
			{ yymsp[0].minor.yy394 = (int)(yymsp[0].major); }
			break;  case  8 :  case  9 :  ;
			{ sqlite3EndTransaction(pParse, (int)(yymsp[-1].major)); }
			break;  case  10 :  { sqlite3Savepoint(pParse, (int)(0), &yymsp[0].minor.yy0); }
			break;  case  11 :  { sqlite3Savepoint(pParse, (int)(1), &yymsp[0].minor.yy0); }
			break;  case  12 :  { sqlite3Savepoint(pParse, (int)(2), &yymsp[0].minor.yy0); }
			break;  case  13 :  { sqlite3StartTable(pParse, &yymsp[-1].minor.yy0, &yymsp[0].minor.yy0, (int)(yymsp[-4].minor.yy394), (int)(0), (int)(0), (int)(yymsp[-2].minor.yy394)); }
			break;  case  14 :  { disableLookaside(pParse); }
			break;  case  15 :  case  18 :  ;  case  47 :  ;  case  62 :  ;  case  72 :  ;  case  81 :  ;  case  98 :  ;  case  242 :  ;
			{ yymsp[1].minor.yy394 = (int)(0); }
			break;  case  16 :  { yymsp[-2].minor.yy394 = (int)(1); }
			break;  case  17 :  { yymsp[0].minor.yy394 = (int)((pParse.db.init.busy) == (0) ? 1 : 0); }
			break;  case  19 :  { sqlite3EndTable(pParse, &yymsp[-2].minor.yy0, &yymsp[-1].minor.yy0, (uint)(yymsp[0].minor.yy285), null); }
			break;  case  20 :  { sqlite3EndTable(pParse, null, null, (uint)(0), yymsp[0].minor.yy47); sqlite3SelectDelete(pParse.db, yymsp[0].minor.yy47); }
			break;  case  21 :  { yymsp[1].minor.yy285 = (uint)(0); }
			break;  case  22 :  { yylhsminor.yy285 = (uint)(yymsp[-2].minor.yy285 | yymsp[0].minor.yy285); }
			yymsp[-2].minor.yy285 = (uint)(yylhsminor.yy285); break;  case  23 :  { if (((yymsp[0].minor.yy0.n) == (5)) && ((sqlite3_strnicmp(yymsp[0].minor.yy0.z, "rowid", (int)(5))) == (0))) { yymsp[-1].minor.yy285 = (uint)(0x00000080 | 0x00000200); } else { yymsp[-1].minor.yy285 = (uint)(0); sqlite3ErrorMsg(pParse, "unknown table option: %.*s", (uint)(yymsp[0].minor.yy0.n), yymsp[0].minor.yy0.z); } }
			break;  case  24 :  { if (((yymsp[0].minor.yy0.n) == (6)) && ((sqlite3_strnicmp(yymsp[0].minor.yy0.z, "strict", (int)(6))) == (0))) { yylhsminor.yy285 = (uint)(0x00010000); } else { yylhsminor.yy285 = (uint)(0); sqlite3ErrorMsg(pParse, "unknown table option: %.*s", (uint)(yymsp[0].minor.yy0.n), yymsp[0].minor.yy0.z); } }
			yymsp[0].minor.yy285 = (uint)(yylhsminor.yy285); break;  case  25 :  { sqlite3AddColumn(pParse, (Token)(yymsp[-1].minor.yy0), (Token)(yymsp[0].minor.yy0)); }
			break;  case  26 :  case  65 :  ;  case  104 :  ;
			{ yymsp[1].minor.yy0.n = (uint)(0); yymsp[1].minor.yy0.z = null; }
			break;  case  27 :  { yymsp[-3].minor.yy0.n = (uint)((int)(&yymsp[0].minor.yy0.z[yymsp[0].minor.yy0.n] - yymsp[-3].minor.yy0.z)); }
			break;  case  28 :  { yymsp[-5].minor.yy0.n = (uint)((int)(&yymsp[0].minor.yy0.z[yymsp[0].minor.yy0.n] - yymsp[-5].minor.yy0.z)); }
			break;  case  29 :  { yymsp[-1].minor.yy0.n = (uint)(yymsp[0].minor.yy0.n + (int)(yymsp[0].minor.yy0.z - yymsp[-1].minor.yy0.z)); }
			break;  case  30 :  { yymsp[1].minor.yy522 = yyLookaheadToken.z; }
			break;  case  31 :  { yymsp[1].minor.yy0 = (Token)(yyLookaheadToken); }
			break;  case  32 :  case  67 :  ;
			{ pParse.constraintName = (Token)(yymsp[0].minor.yy0); }
			break;  case  33 :  { sqlite3AddDefaultValue(pParse, yymsp[0].minor.yy528, yymsp[-1].minor.yy0.z, &yymsp[-1].minor.yy0.z[yymsp[-1].minor.yy0.n]); }
			break;  case  34 :  { sqlite3AddDefaultValue(pParse, yymsp[-1].minor.yy528, yymsp[-2].minor.yy0.z + 1, yymsp[0].minor.yy0.z); }
			break;  case  35 :  { sqlite3AddDefaultValue(pParse, yymsp[0].minor.yy528, yymsp[-2].minor.yy0.z, &yymsp[-1].minor.yy0.z[yymsp[-1].minor.yy0.n]); }
			break;  case  36 :  { Expr p = sqlite3PExpr(pParse, (int)(173), yymsp[0].minor.yy528, null); sqlite3AddDefaultValue(pParse, p, yymsp[-2].minor.yy0.z, &yymsp[-1].minor.yy0.z[yymsp[-1].minor.yy0.n]); }
			break;  case  37 :  { Expr p = tokenExpr(pParse, (int)(117), (Token)(yymsp[0].minor.yy0)); if ((p) != null) { sqlite3ExprIdToTrueFalse(p); } sqlite3AddDefaultValue(pParse, p, yymsp[0].minor.yy0.z, yymsp[0].minor.yy0.z + yymsp[0].minor.yy0.n); }
			break;  case  38 :  { sqlite3AddNotNull(pParse, (int)(yymsp[0].minor.yy394)); }
			break;  case  39 :  { sqlite3AddPrimaryKey(pParse, null, (int)(yymsp[-1].minor.yy394), (int)(yymsp[0].minor.yy394), (int)(yymsp[-2].minor.yy394)); }
			break;  case  40 :  { sqlite3CreateIndex(pParse, null, null, null, null, (int)(yymsp[0].minor.yy394), null, null, (int)(0), (int)(0), (byte)(1)); }
			break;  case  41 :  { sqlite3AddCheckConstraint(pParse, yymsp[-1].minor.yy528, yymsp[-2].minor.yy0.z, yymsp[0].minor.yy0.z); }
			break;  case  42 :  { sqlite3CreateForeignKey(pParse, null, &yymsp[-2].minor.yy0, yymsp[-1].minor.yy322, (int)(yymsp[0].minor.yy394)); }
			break;  case  43 :  { sqlite3DeferForeignKey(pParse, (int)(yymsp[0].minor.yy394)); }
			break;  case  44 :  { sqlite3AddCollateType(pParse, &yymsp[0].minor.yy0); }
			break;  case  45 :  { sqlite3AddGenerated(pParse, yymsp[-1].minor.yy528, null); }
			break;  case  46 :  { sqlite3AddGenerated(pParse, yymsp[-2].minor.yy528, &yymsp[0].minor.yy0); }
			break;  case  48 :  { yymsp[0].minor.yy394 = (int)(1); }
			break;  case  49 :  { yymsp[1].minor.yy394 = (int)(0 * 0x0101); }
			break;  case  50 :  { yymsp[-1].minor.yy394 = (int)((yymsp[-1].minor.yy394 & ~yymsp[0].minor.yy231.mask) | yymsp[0].minor.yy231.value); }
			break;  case  51 :  { yymsp[-1].minor.yy231.value = (int)(0); yymsp[-1].minor.yy231.mask = (int)(0x000000); }
			break;  case  52 :  { yymsp[-2].minor.yy231.value = (int)(0); yymsp[-2].minor.yy231.mask = (int)(0x000000); }
			break;  case  53 :  { yymsp[-2].minor.yy231.value = (int)(yymsp[0].minor.yy394); yymsp[-2].minor.yy231.mask = (int)(0x0000ff); }
			break;  case  54 :  { yymsp[-2].minor.yy231.value = (int)(yymsp[0].minor.yy394 << 8); yymsp[-2].minor.yy231.mask = (int)(0x00ff00); }
			break;  case  55 :  { yymsp[-1].minor.yy394 = (int)(8); }
			break;  case  56 :  { yymsp[-1].minor.yy394 = (int)(9); }
			break;  case  57 :  { yymsp[0].minor.yy394 = (int)(10); }
			break;  case  58 :  { yymsp[0].minor.yy394 = (int)(7); }
			break;  case  59 :  { yymsp[-1].minor.yy394 = (int)(0); }
			break;  case  60 :  { yymsp[-2].minor.yy394 = (int)(0); }
			break;  case  61 :  case  76 :  ;  case  171 :  ;
			{ yymsp[-1].minor.yy394 = (int)(yymsp[0].minor.yy394); }
			break;  case  63 :  case  80 :  ;  case  214 :  ;  case  217 :  ;  case  243 :  ;
			{ yymsp[-1].minor.yy394 = (int)(1); }
			break;  case  64 :  { yymsp[-1].minor.yy394 = (int)(0); }
			break;  case  66 :  { pParse.constraintName.n = (uint)(0); }
			break;  case  68 :  { sqlite3AddPrimaryKey(pParse, yymsp[-3].minor.yy322, (int)(yymsp[0].minor.yy394), (int)(yymsp[-2].minor.yy394), (int)(0)); }
			break;  case  69 :  { sqlite3CreateIndex(pParse, null, null, null, yymsp[-2].minor.yy322, (int)(yymsp[0].minor.yy394), null, null, (int)(0), (int)(0), (byte)(1)); }
			break;  case  70 :  { sqlite3AddCheckConstraint(pParse, yymsp[-2].minor.yy528, yymsp[-3].minor.yy0.z, yymsp[-1].minor.yy0.z); }
			break;  case  71 :  { sqlite3CreateForeignKey(pParse, yymsp[-6].minor.yy322, &yymsp[-3].minor.yy0, yymsp[-2].minor.yy322, (int)(yymsp[-1].minor.yy394)); sqlite3DeferForeignKey(pParse, (int)(yymsp[0].minor.yy394)); }
			break;  case  73 :  case  75 :  ;
			{ yymsp[1].minor.yy394 = (int)(11); }
			break;  case  74 :  { yymsp[-2].minor.yy394 = (int)(yymsp[0].minor.yy394); }
			break;  case  77 :  { yymsp[0].minor.yy394 = (int)(4); }
			break;  case  78 :  case  172 :  ;
			{ yymsp[0].minor.yy394 = (int)(5); }
			break;  case  79 :  { sqlite3DropTable(pParse, yymsp[0].minor.yy131, (int)(0), (int)(yymsp[-1].minor.yy394)); }
			break;  case  82 :  { sqlite3CreateView(pParse, &yymsp[-8].minor.yy0, &yymsp[-4].minor.yy0, &yymsp[-3].minor.yy0, yymsp[-2].minor.yy322, yymsp[0].minor.yy47, (int)(yymsp[-7].minor.yy394), (int)(yymsp[-5].minor.yy394)); }
			break;  case  83 :  { sqlite3DropTable(pParse, yymsp[0].minor.yy131, (int)(1), (int)(yymsp[-1].minor.yy394)); }
			break;  case  84 :  { SelectDest dest = (SelectDest)(stackalloc SelectDest[] { 9, 0, 0, 0, 0, null, null } ; ) ; sqlite3Select(pParse, yymsp[0].minor.yy47, dest); sqlite3SelectDelete(pParse.db, yymsp[0].minor.yy47); }
			break;  case  85 :  { yymsp[-2].minor.yy47 = attachWithToSelect(pParse, yymsp[0].minor.yy47, yymsp[-1].minor.yy521); }
			break;  case  86 :  { yymsp[-3].minor.yy47 = attachWithToSelect(pParse, yymsp[0].minor.yy47, yymsp[-1].minor.yy521); }
			break;  case  87 :  { Select p = yymsp[0].minor.yy47; if ((p) != null) { parserDoubleLinkSelect(pParse, p); } yymsp[0].minor.yy47 = p; }
			break;  case  88 :  { Select pRhs = yymsp[0].minor.yy47; Select pLhs = yymsp[-2].minor.yy47; if (((pRhs) != null) && ((pRhs.pPrior) != null)) { SrcList pFrom; Token x = new Token(); x.n = (uint)(0); parserDoubleLinkSelect(pParse, pRhs); pFrom = sqlite3SrcListAppendFromTerm(pParse, null, null, null, &x, pRhs, null, null); pRhs = sqlite3SelectNew(pParse, null, pFrom, null, null, null, null, (uint)(0), null); } if ((pRhs) != null) { pRhs.op = ((byte)(yymsp[-1].minor.yy394)); pRhs.pPrior = pLhs; if ((pLhs) != null) pLhs.selFlags &= (uint)(~0x0000400); pRhs.selFlags &= (uint)(~0x0000400); if (yymsp[-1].minor.yy394 != 135) pParse.hasCompound = (byte)(1); } else { sqlite3SelectDelete(pParse.db, pLhs); } yymsp[-2].minor.yy47 = pRhs; }
			break;  case  89 :  case  91 :  ;
			{ yymsp[0].minor.yy394 = (int)(yymsp[0].major); }
			break;  case  90 :  { yymsp[-1].minor.yy394 = (int)(135); }
			break;  case  92 :  { yymsp[-8].minor.yy47 = sqlite3SelectNew(pParse, yymsp[-6].minor.yy322, yymsp[-5].minor.yy131, yymsp[-4].minor.yy528, yymsp[-3].minor.yy322, yymsp[-2].minor.yy528, yymsp[-1].minor.yy322, (uint)(yymsp[-7].minor.yy394), yymsp[0].minor.yy528); }
			break;  case  93 :  { yymsp[-9].minor.yy47 = sqlite3SelectNew(pParse, yymsp[-7].minor.yy322, yymsp[-6].minor.yy131, yymsp[-5].minor.yy528, yymsp[-4].minor.yy322, yymsp[-3].minor.yy528, yymsp[-1].minor.yy322, (uint)(yymsp[-8].minor.yy394), yymsp[0].minor.yy528); if ((yymsp[-9].minor.yy47) != null) { yymsp[-9].minor.yy47.pWinDefn = yymsp[-2].minor.yy41; } else { sqlite3WindowListDelete(pParse.db, yymsp[-2].minor.yy41); } }
			break;  case  94 :  { yymsp[-3].minor.yy47 = sqlite3SelectNew(pParse, yymsp[-1].minor.yy322, null, null, null, null, null, (uint)(0x0000200), null); }
			break;  case  95 :  { Select pRight; Select pLeft = yymsp[-4].minor.yy47; pRight = sqlite3SelectNew(pParse, yymsp[-1].minor.yy322, null, null, null, null, null, (uint)(0x0000200 | 0x0000400), null); if ((pLeft) != null) pLeft.selFlags &= (uint)(~0x0000400); if ((pRight) != null) { pRight.op = (byte)(135); pRight.pPrior = pLeft; yymsp[-4].minor.yy47 = pRight; } else { yymsp[-4].minor.yy47 = pLeft; } }
			break;  case  96 :  { yymsp[0].minor.yy394 = (int)(0x0000001); }
			break;  case  97 :  { yymsp[0].minor.yy394 = (int)(0x0000002); }
			break;  case  99 :  case  132 :  ;  case  142 :  ;  case  230 :  ;  case  233 :  ;  case  238 :  ;
			{ yymsp[1].minor.yy322 = null; }
			break;  case  100 :  { yymsp[-4].minor.yy322 = sqlite3ExprListAppend(pParse, yymsp[-4].minor.yy322, yymsp[-2].minor.yy528); if ((yymsp[0].minor.yy0.n) > (0)) sqlite3ExprListSetName(pParse, yymsp[-4].minor.yy322, &yymsp[0].minor.yy0, (int)(1)); sqlite3ExprListSetSpan(pParse, yymsp[-4].minor.yy322, yymsp[-3].minor.yy522, yymsp[-1].minor.yy522); }
			break;  case  101 :  { Expr p = sqlite3Expr(pParse.db, (int)(180), null); yymsp[-2].minor.yy322 = sqlite3ExprListAppend(pParse, yymsp[-2].minor.yy322, p); }
			break;  case  102 :  { Expr pRight = sqlite3PExpr(pParse, (int)(180), null, null); Expr pLeft = tokenExpr(pParse, (int)(59), (Token)(yymsp[-2].minor.yy0)); Expr pDot = sqlite3PExpr(pParse, (int)(141), pLeft, pRight); yymsp[-4].minor.yy322 = sqlite3ExprListAppend(pParse, yymsp[-4].minor.yy322, pDot); }
			break;  case  103 :  case  114 :  ;  case  254 :  ;  case  255 :  ;
			{ yymsp[-1].minor.yy0 = (Token)(yymsp[0].minor.yy0); }
			break;  case  105 :  case  108 :  ;
			{ yymsp[1].minor.yy131 = null; }
			break;  case  106 :  { yymsp[-1].minor.yy131 = yymsp[0].minor.yy131; sqlite3SrcListShiftJoinType(yymsp[-1].minor.yy131); }
			break;  case  107 :  { if ((((yymsp[-1].minor.yy131) != null) && ((yymsp[-1].minor.yy131.nSrc) > (0)))) yymsp[-1].minor.yy131.a[yymsp[-1].minor.yy131.nSrc - 1].fg.jointype = ((byte)(yymsp[0].minor.yy394)); }
			break;  case  109 :  { yymsp[-6].minor.yy131 = sqlite3SrcListAppendFromTerm(pParse, yymsp[-6].minor.yy131, &yymsp[-5].minor.yy0, &yymsp[-4].minor.yy0, &yymsp[-3].minor.yy0, null, yymsp[-1].minor.yy528, yymsp[0].minor.yy254); sqlite3SrcListIndexedBy(pParse, yymsp[-6].minor.yy131, &yymsp[-2].minor.yy0); }
			break;  case  110 :  { yymsp[-8].minor.yy131 = sqlite3SrcListAppendFromTerm(pParse, yymsp[-8].minor.yy131, &yymsp[-7].minor.yy0, &yymsp[-6].minor.yy0, &yymsp[-2].minor.yy0, null, yymsp[-1].minor.yy528, yymsp[0].minor.yy254); sqlite3SrcListFuncArgs(pParse, yymsp[-8].minor.yy131, yymsp[-4].minor.yy322); }
			break;  case  111 :  { yymsp[-6].minor.yy131 = sqlite3SrcListAppendFromTerm(pParse, yymsp[-6].minor.yy131, null, null, &yymsp[-2].minor.yy0, yymsp[-4].minor.yy47, yymsp[-1].minor.yy528, yymsp[0].minor.yy254); }
			break;  case  112 :  { if (((((yymsp[-6].minor.yy131) == (null)) && ((yymsp[-2].minor.yy0.n) == (0))) && ((yymsp[-1].minor.yy528) == (null))) && ((yymsp[0].minor.yy254) == (null))) { yymsp[-6].minor.yy131 = yymsp[-4].minor.yy131; } else if ((yymsp[-4].minor.yy131.nSrc) == (1)) { yymsp[-6].minor.yy131 = sqlite3SrcListAppendFromTerm(pParse, yymsp[-6].minor.yy131, null, null, &yymsp[-2].minor.yy0, null, yymsp[-1].minor.yy528, yymsp[0].minor.yy254); if ((yymsp[-6].minor.yy131) != null) { SrcItem pNew = yymsp[-6].minor.yy131.a[yymsp[-6].minor.yy131.nSrc - 1]; SrcItem pOld = yymsp[-4].minor.yy131.a; pNew.zName = pOld.zName; pNew.zDatabase = pOld.zDatabase; pNew.pSelect = pOld.pSelect; if ((pOld.fg.isTabFunc) != 0) { pNew.u1.pFuncArg = pOld.u1.pFuncArg; pOld.u1.pFuncArg = null; pOld.fg.isTabFunc = (uint)(0); pNew.fg.isTabFunc = (uint)(1); } pOld.zName = pOld.zDatabase = null; pOld.pSelect = null; } sqlite3SrcListDelete(pParse.db, yymsp[-4].minor.yy131); } else { Select pSubquery; sqlite3SrcListShiftJoinType(yymsp[-4].minor.yy131); pSubquery = sqlite3SelectNew(pParse, null, yymsp[-4].minor.yy131, null, null, null, null, (uint)(0x0000800), null); yymsp[-6].minor.yy131 = sqlite3SrcListAppendFromTerm(pParse, yymsp[-6].minor.yy131, null, null, &yymsp[-2].minor.yy0, pSubquery, yymsp[-1].minor.yy528, yymsp[0].minor.yy254); } }
			break;  case  113 :  case  127 :  ;
			{ yymsp[1].minor.yy0.z = null; yymsp[1].minor.yy0.n = (uint)(0); }
			break;  case  115 :  { yylhsminor.yy131 = sqlite3SrcListAppend(pParse, null, &yymsp[0].minor.yy0, null); if (((pParse.eParseMode) >= (2)) && ((yylhsminor.yy131) != null)) sqlite3RenameTokenMap(pParse, yylhsminor.yy131.a[0].zName, &yymsp[0].minor.yy0); }
			yymsp[0].minor.yy131 = yylhsminor.yy131; break;  case  116 :  { yylhsminor.yy131 = sqlite3SrcListAppend(pParse, null, &yymsp[-2].minor.yy0, &yymsp[0].minor.yy0); if (((pParse.eParseMode) >= (2)) && ((yylhsminor.yy131) != null)) sqlite3RenameTokenMap(pParse, yylhsminor.yy131.a[0].zName, &yymsp[0].minor.yy0); }
			yymsp[-2].minor.yy131 = yylhsminor.yy131; break;  case  117 :  { yymsp[0].minor.yy131 = sqlite3SrcListAppend(pParse, null, &yymsp[0].minor.yy0, null); }
			break;  case  118 :  { yymsp[-2].minor.yy131 = sqlite3SrcListAppend(pParse, null, &yymsp[-2].minor.yy0, &yymsp[0].minor.yy0); }
			break;  case  119 :  { yymsp[-4].minor.yy131 = sqlite3SrcListAppend(pParse, null, &yymsp[-4].minor.yy0, &yymsp[-2].minor.yy0); if ((yymsp[-4].minor.yy131) != null) yymsp[-4].minor.yy131.a[0].zAlias = sqlite3NameFromToken(pParse.db, &yymsp[0].minor.yy0); }
			break;  case  120 :  { yymsp[-2].minor.yy131 = sqlite3SrcListAppend(pParse, null, &yymsp[-2].minor.yy0, null); if ((yymsp[-2].minor.yy131) != null) yymsp[-2].minor.yy131.a[0].zAlias = sqlite3NameFromToken(pParse.db, &yymsp[0].minor.yy0); }
			break;  case  121 :  { yymsp[0].minor.yy394 = (int)(0x0001); }
			break;  case  122 :  { yymsp[-1].minor.yy394 = (int)(sqlite3JoinType(pParse, &yymsp[-1].minor.yy0, null, null)); }
			break;  case  123 :  { yymsp[-2].minor.yy394 = (int)(sqlite3JoinType(pParse, &yymsp[-2].minor.yy0, &yymsp[-1].minor.yy0, null)); }
			break;  case  124 :  { yymsp[-3].minor.yy394 = (int)(sqlite3JoinType(pParse, &yymsp[-3].minor.yy0, &yymsp[-2].minor.yy0, &yymsp[-1].minor.yy0)); }
			break;  case  125 :  case  145 :  ;  case  152 :  ;  case  154 :  ;  case  226 :  ;  case  247 :  ;
			{ yymsp[-1].minor.yy528 = yymsp[0].minor.yy528; }
			break;  case  126 :  case  144 :  ;  case  146 :  ;  case  151 :  ;  case  153 :  ;  case  227 :  ;  case  229 :  ;  case  248 :  ;
			{ yymsp[1].minor.yy528 = null; }
			break;  case  128 :  { yymsp[-2].minor.yy0 = (Token)(yymsp[0].minor.yy0); }
			break;  case  129 :  { yymsp[-1].minor.yy0.z = null; yymsp[-1].minor.yy0.n = (uint)(1); }
			break;  case  130 :  { yymsp[-3].minor.yy254 = yymsp[-1].minor.yy254; }
			break;  case  131 :  case  173 :  ;
			{ yymsp[1].minor.yy254 = null; }
			break;  case  133 :  case  143 :  ;
			{ yymsp[-2].minor.yy322 = yymsp[0].minor.yy322; }
			break;  case  134 :  { yymsp[-4].minor.yy322 = sqlite3ExprListAppend(pParse, yymsp[-4].minor.yy322, yymsp[-2].minor.yy528); sqlite3ExprListSetSortOrder(yymsp[-4].minor.yy322, (int)(yymsp[-1].minor.yy394), (int)(yymsp[0].minor.yy394)); }
			break;  case  135 :  { yymsp[-2].minor.yy322 = sqlite3ExprListAppend(pParse, null, yymsp[-2].minor.yy528); sqlite3ExprListSetSortOrder(yymsp[-2].minor.yy322, (int)(yymsp[-1].minor.yy394), (int)(yymsp[0].minor.yy394)); }
			break;  case  136 :  { yymsp[0].minor.yy394 = (int)(0); }
			break;  case  137 :  { yymsp[0].minor.yy394 = (int)(1); }
			break;  case  138 :  case  141 :  ;
			{ yymsp[1].minor.yy394 = (int)(-1); }
			break;  case  139 :  { yymsp[-1].minor.yy394 = (int)(0); }
			break;  case  140 :  { yymsp[-1].minor.yy394 = (int)(1); }
			break;  case  147 :  { yymsp[-1].minor.yy528 = sqlite3PExpr(pParse, (int)(148), yymsp[0].minor.yy528, null); }
			break;  case  148 :  { yymsp[-3].minor.yy528 = sqlite3PExpr(pParse, (int)(148), yymsp[-2].minor.yy528, yymsp[0].minor.yy528); }
			break;  case  149 :  { yymsp[-3].minor.yy528 = sqlite3PExpr(pParse, (int)(148), yymsp[0].minor.yy528, yymsp[-2].minor.yy528); }
			break;  case  150 :  { sqlite3SrcListIndexedBy(pParse, yymsp[-2].minor.yy131, &yymsp[-1].minor.yy0); sqlite3DeleteFrom(pParse, yymsp[-2].minor.yy131, yymsp[0].minor.yy528, null, null); }
			break;  case  155 :  { sqlite3AddReturning(pParse, yymsp[0].minor.yy322); yymsp[-1].minor.yy528 = null; }
			break;  case  156 :  { sqlite3AddReturning(pParse, yymsp[0].minor.yy322); yymsp[-3].minor.yy528 = yymsp[-2].minor.yy528; }
			break;  case  157 :  { sqlite3SrcListIndexedBy(pParse, yymsp[-5].minor.yy131, &yymsp[-4].minor.yy0); sqlite3ExprListCheckLength(pParse, yymsp[-2].minor.yy322, "set list"); yymsp[-5].minor.yy131 = sqlite3SrcListAppendList(pParse, yymsp[-5].minor.yy131, yymsp[-1].minor.yy131); sqlite3Update(pParse, yymsp[-5].minor.yy131, yymsp[-2].minor.yy322, yymsp[0].minor.yy528, (int)(yymsp[-6].minor.yy394), null, null, null); }
			break;  case  158 :  { yymsp[-4].minor.yy322 = sqlite3ExprListAppend(pParse, yymsp[-4].minor.yy322, yymsp[0].minor.yy528); sqlite3ExprListSetName(pParse, yymsp[-4].minor.yy322, &yymsp[-2].minor.yy0, (int)(1)); }
			break;  case  159 :  { yymsp[-6].minor.yy322 = sqlite3ExprListAppendVector(pParse, yymsp[-6].minor.yy322, yymsp[-3].minor.yy254, yymsp[0].minor.yy528); }
			break;  case  160 :  { yylhsminor.yy322 = sqlite3ExprListAppend(pParse, null, yymsp[0].minor.yy528); sqlite3ExprListSetName(pParse, yylhsminor.yy322, &yymsp[-2].minor.yy0, (int)(1)); }
			yymsp[-2].minor.yy322 = yylhsminor.yy322; break;  case  161 :  { yymsp[-4].minor.yy322 = sqlite3ExprListAppendVector(pParse, null, yymsp[-3].minor.yy254, yymsp[0].minor.yy528); }
			break;  case  162 :  { sqlite3Insert(pParse, yymsp[-3].minor.yy131, yymsp[-1].minor.yy47, yymsp[-2].minor.yy254, (int)(yymsp[-5].minor.yy394), yymsp[0].minor.yy444); }
			break;  case  163 :  { sqlite3Insert(pParse, yymsp[-4].minor.yy131, null, yymsp[-3].minor.yy254, (int)(yymsp[-6].minor.yy394), null); }
			break;  case  164 :  { yymsp[1].minor.yy444 = null; }
			break;  case  165 :  { yymsp[-1].minor.yy444 = null; sqlite3AddReturning(pParse, yymsp[0].minor.yy322); }
			break;  case  166 :  { yymsp[-11].minor.yy444 = sqlite3UpsertNew(pParse.db, yymsp[-8].minor.yy322, yymsp[-6].minor.yy528, yymsp[-2].minor.yy322, yymsp[-1].minor.yy528, yymsp[0].minor.yy444); }
			break;  case  167 :  { yymsp[-8].minor.yy444 = sqlite3UpsertNew(pParse.db, yymsp[-5].minor.yy322, yymsp[-3].minor.yy528, null, null, yymsp[0].minor.yy444); }
			break;  case  168 :  { yymsp[-4].minor.yy444 = sqlite3UpsertNew(pParse.db, null, null, null, null, null); }
			break;  case  169 :  { yymsp[-7].minor.yy444 = sqlite3UpsertNew(pParse.db, null, null, yymsp[-2].minor.yy322, yymsp[-1].minor.yy528, null); }
			break;  case  170 :  { sqlite3AddReturning(pParse, yymsp[0].minor.yy322); }
			break;  case  174 :  { yymsp[-2].minor.yy254 = yymsp[-1].minor.yy254; }
			break;  case  175 :  { yymsp[-2].minor.yy254 = sqlite3IdListAppend(pParse, yymsp[-2].minor.yy254, &yymsp[0].minor.yy0); }
			break;  case  176 :  { yymsp[0].minor.yy254 = sqlite3IdListAppend(pParse, null, &yymsp[0].minor.yy0); }
			break;  case  177 :  { yymsp[-2].minor.yy528 = yymsp[-1].minor.yy528; }
			break;  case  178 :  case  179 :  ;
			{ yymsp[0].minor.yy528 = tokenExpr(pParse, (int)(59), (Token)(yymsp[0].minor.yy0)); }
			break;  case  180 :  { Expr temp1 = tokenExpr(pParse, (int)(59), (Token)(yymsp[-2].minor.yy0)); Expr temp2 = tokenExpr(pParse, (int)(59), (Token)(yymsp[0].minor.yy0)); yylhsminor.yy528 = sqlite3PExpr(pParse, (int)(141), temp1, temp2); }
			yymsp[-2].minor.yy528 = yylhsminor.yy528; break;  case  181 :  { Expr temp1 = tokenExpr(pParse, (int)(59), (Token)(yymsp[-4].minor.yy0)); Expr temp2 = tokenExpr(pParse, (int)(59), (Token)(yymsp[-2].minor.yy0)); Expr temp3 = tokenExpr(pParse, (int)(59), (Token)(yymsp[0].minor.yy0)); Expr temp4 = sqlite3PExpr(pParse, (int)(141), temp2, temp3); if (((pParse.eParseMode) >= (2))) { sqlite3RenameTokenRemap(pParse, null, temp1); } yylhsminor.yy528 = sqlite3PExpr(pParse, (int)(141), temp1, temp4); }
			yymsp[-4].minor.yy528 = yylhsminor.yy528; break;  case  182 :  case  183 :  ;
			{ yymsp[0].minor.yy528 = tokenExpr(pParse, (int)(yymsp[0].major), (Token)(yymsp[0].minor.yy0)); }
			break;  case  184 :  { yylhsminor.yy528 = sqlite3ExprAlloc(pParse.db, (int)(155), &yymsp[0].minor.yy0, (int)(1)); if ((yylhsminor.yy528) != null) yylhsminor.yy528.w.iOfst = ((int)(yymsp[0].minor.yy0.z - pParse.zTail)); }
			yymsp[0].minor.yy528 = yylhsminor.yy528; break;  case  185 :  { if (!(((yymsp[0].minor.yy0.z[0]) == (35)) && ((sqlite3CtypeMap[(byte)(yymsp[0].minor.yy0.z[1])] & 0x04) != 0))) { uint n = (uint)(yymsp[0].minor.yy0.n); yymsp[0].minor.yy528 = tokenExpr(pParse, (int)(156), (Token)(yymsp[0].minor.yy0)); sqlite3ExprAssignVarNumber(pParse, yymsp[0].minor.yy528, (uint)(n)); } else { Token t = (Token)(yymsp[0].minor.yy0); if ((pParse.nested) == (0)) { sqlite3ErrorMsg(pParse, "near \"%T\": syntax error", &t); yymsp[0].minor.yy528 = null; } else { yymsp[0].minor.yy528 = sqlite3PExpr(pParse, (int)(176), null, null); if ((yymsp[0].minor.yy528) != null) sqlite3GetInt32(&t.z[1], &yymsp[0].minor.yy528.iTable); } } }
			break;  case  186 :  { yymsp[-2].minor.yy528 = sqlite3ExprAddCollateToken(pParse, yymsp[-2].minor.yy528, &yymsp[0].minor.yy0, (int)(1)); }
			break;  case  187 :  { yymsp[-5].minor.yy528 = sqlite3ExprAlloc(pParse.db, (int)(36), &yymsp[-1].minor.yy0, (int)(1)); sqlite3ExprAttachSubtrees(pParse.db, yymsp[-5].minor.yy528, yymsp[-3].minor.yy528, null); }
			break;  case  188 :  { yylhsminor.yy528 = sqlite3ExprFunction(pParse, yymsp[-1].minor.yy322, &yymsp[-4].minor.yy0, (int)(yymsp[-2].minor.yy394)); }
			yymsp[-4].minor.yy528 = yylhsminor.yy528; break;  case  189 :  { yylhsminor.yy528 = sqlite3ExprFunction(pParse, null, &yymsp[-3].minor.yy0, (int)(0)); }
			yymsp[-3].minor.yy528 = yylhsminor.yy528; break;  case  190 :  { yylhsminor.yy528 = sqlite3ExprFunction(pParse, yymsp[-2].minor.yy322, &yymsp[-5].minor.yy0, (int)(yymsp[-3].minor.yy394)); sqlite3WindowAttach(pParse, yylhsminor.yy528, yymsp[0].minor.yy41); }
			yymsp[-5].minor.yy528 = yylhsminor.yy528; break;  case  191 :  { yylhsminor.yy528 = sqlite3ExprFunction(pParse, null, &yymsp[-4].minor.yy0, (int)(0)); sqlite3WindowAttach(pParse, yylhsminor.yy528, yymsp[0].minor.yy41); }
			yymsp[-4].minor.yy528 = yylhsminor.yy528; break;  case  192 :  { yylhsminor.yy528 = sqlite3ExprFunction(pParse, null, &yymsp[0].minor.yy0, (int)(0)); }
			yymsp[0].minor.yy528 = yylhsminor.yy528; break;  case  193 :  { ExprList pList = sqlite3ExprListAppend(pParse, yymsp[-3].minor.yy322, yymsp[-1].minor.yy528); yymsp[-4].minor.yy528 = sqlite3PExpr(pParse, (int)(177), null, null); if ((yymsp[-4].minor.yy528) != null) { yymsp[-4].minor.yy528.x.pList = pList; if ((pList.nExpr) != 0) { yymsp[-4].minor.yy528.flags |= (uint)(pList.a[0].pExpr.flags & (0x000100 | 0x200000 | 0x000004)); } } else { sqlite3ExprListDelete(pParse.db, pList); } }
			break;  case  194 :  { yymsp[-2].minor.yy528 = sqlite3ExprAnd(pParse, yymsp[-2].minor.yy528, yymsp[0].minor.yy528); }
			break;  case  195 :  case  196 :  ;  case  197 :  ;  case  198 :  ;  case  199 :  ;  case  200 :  ;  case  201 :  ;
			{ yymsp[-2].minor.yy528 = sqlite3PExpr(pParse, (int)(yymsp[-1].major), yymsp[-2].minor.yy528, yymsp[0].minor.yy528); }
			break;  case  202 :  { yymsp[-1].minor.yy0 = (Token)(yymsp[0].minor.yy0); yymsp[-1].minor.yy0.n |= (uint)(0x80000000); }
			break;  case  203 :  { ExprList pList; int bNot = (int)(yymsp[-1].minor.yy0.n & 0x80000000); yymsp[-1].minor.yy0.n &= (uint)(0x7fffffff); pList = sqlite3ExprListAppend(pParse, null, yymsp[0].minor.yy528); pList = sqlite3ExprListAppend(pParse, pList, yymsp[-2].minor.yy528); yymsp[-2].minor.yy528 = sqlite3ExprFunction(pParse, pList, &yymsp[-1].minor.yy0, (int)(0)); if ((bNot) != 0) yymsp[-2].minor.yy528 = sqlite3PExpr(pParse, (int)(19), yymsp[-2].minor.yy528, null); if ((yymsp[-2].minor.yy528) != null) yymsp[-2].minor.yy528.flags |= (uint)(0x000080); }
			break;  case  204 :  { ExprList pList; int bNot = (int)(yymsp[-3].minor.yy0.n & 0x80000000); yymsp[-3].minor.yy0.n &= (uint)(0x7fffffff); pList = sqlite3ExprListAppend(pParse, null, yymsp[-2].minor.yy528); pList = sqlite3ExprListAppend(pParse, pList, yymsp[-4].minor.yy528); pList = sqlite3ExprListAppend(pParse, pList, yymsp[0].minor.yy528); yymsp[-4].minor.yy528 = sqlite3ExprFunction(pParse, pList, &yymsp[-3].minor.yy0, (int)(0)); if ((bNot) != 0) yymsp[-4].minor.yy528 = sqlite3PExpr(pParse, (int)(19), yymsp[-4].minor.yy528, null); if ((yymsp[-4].minor.yy528) != null) yymsp[-4].minor.yy528.flags |= (uint)(0x000080); }
			break;  case  205 :  { yymsp[-1].minor.yy528 = sqlite3PExpr(pParse, (int)(yymsp[0].major), yymsp[-1].minor.yy528, null); }
			break;  case  206 :  { yymsp[-2].minor.yy528 = sqlite3PExpr(pParse, (int)(51), yymsp[-2].minor.yy528, null); }
			break;  case  207 :  { yymsp[-2].minor.yy528 = sqlite3PExpr(pParse, (int)(45), yymsp[-2].minor.yy528, yymsp[0].minor.yy528); binaryToUnaryIfNull(pParse, yymsp[0].minor.yy528, yymsp[-2].minor.yy528, (int)(50)); }
			break;  case  208 :  { yymsp[-3].minor.yy528 = sqlite3PExpr(pParse, (int)(171), yymsp[-3].minor.yy528, yymsp[0].minor.yy528); binaryToUnaryIfNull(pParse, yymsp[0].minor.yy528, yymsp[-3].minor.yy528, (int)(51)); }
			break;  case  209 :  case  210 :  ;
			{ yymsp[-1].minor.yy528 = sqlite3PExpr(pParse, (int)(yymsp[-1].major), yymsp[0].minor.yy528, null); }
			break;  case  211 :  { yymsp[-1].minor.yy528 = sqlite3PExpr(pParse, (int)((yymsp[-1].major) == (106) ? 174 : 173), yymsp[0].minor.yy528, null); }
			break;  case  212 :  { ExprList pList = sqlite3ExprListAppend(pParse, null, yymsp[-2].minor.yy528); pList = sqlite3ExprListAppend(pParse, pList, yymsp[0].minor.yy528); yylhsminor.yy528 = sqlite3ExprFunction(pParse, pList, &yymsp[-1].minor.yy0, (int)(0)); }
			yymsp[-2].minor.yy528 = yylhsminor.yy528; break;  case  213 :  case  216 :  ;
			{ yymsp[0].minor.yy394 = (int)(0); }
			break;  case  215 :  { ExprList pList = sqlite3ExprListAppend(pParse, null, yymsp[-2].minor.yy528); pList = sqlite3ExprListAppend(pParse, pList, yymsp[0].minor.yy528); yymsp[-4].minor.yy528 = sqlite3PExpr(pParse, (int)(48), yymsp[-4].minor.yy528, null); if ((yymsp[-4].minor.yy528) != null) { yymsp[-4].minor.yy528.x.pList = pList; } else { sqlite3ExprListDelete(pParse.db, pList); } if ((yymsp[-3].minor.yy394) != 0) yymsp[-4].minor.yy528 = sqlite3PExpr(pParse, (int)(19), yymsp[-4].minor.yy528, null); }
			break;  case  218 :  { if ((yymsp[-1].minor.yy322) == (null)) { sqlite3ExprUnmapAndDelete(pParse, yymsp[-4].minor.yy528); yymsp[-4].minor.yy528 = sqlite3Expr(pParse.db, (int)(155), (yymsp[-3].minor.yy394) != 0 ? "1" : "0"); } else { Expr pRHS = yymsp[-1].minor.yy322.a[0].pExpr; if ((((yymsp[-1].minor.yy322.nExpr) == (1)) && ((sqlite3ExprIsConstant(pRHS)) != 0)) && (yymsp[-4].minor.yy528.op != 177)) { yymsp[-1].minor.yy322.a[0].pExpr = null; sqlite3ExprListDelete(pParse.db, yymsp[-1].minor.yy322); pRHS = sqlite3PExpr(pParse, (int)(174), pRHS, null); yymsp[-4].minor.yy528 = sqlite3PExpr(pParse, (int)(53), yymsp[-4].minor.yy528, pRHS); } else { yymsp[-4].minor.yy528 = sqlite3PExpr(pParse, (int)(49), yymsp[-4].minor.yy528, null); if ((yymsp[-4].minor.yy528) == (null)) { sqlite3ExprListDelete(pParse.db, yymsp[-1].minor.yy322); } else if ((yymsp[-4].minor.yy528.pLeft.op) == (177)) { int nExpr = (int)(yymsp[-4].minor.yy528.pLeft.x.pList.nExpr); Select pSelectRHS = sqlite3ExprListToValues(pParse, (int)(nExpr), yymsp[-1].minor.yy322); if ((pSelectRHS) != null) { parserDoubleLinkSelect(pParse, pSelectRHS); sqlite3PExprAddSelect(pParse, yymsp[-4].minor.yy528, pSelectRHS); } } else { yymsp[-4].minor.yy528.x.pList = yymsp[-1].minor.yy322; sqlite3ExprSetHeightAndFlags(pParse, yymsp[-4].minor.yy528); } } if ((yymsp[-3].minor.yy394) != 0) yymsp[-4].minor.yy528 = sqlite3PExpr(pParse, (int)(19), yymsp[-4].minor.yy528, null); } }
			break;  case  219 :  { yymsp[-2].minor.yy528 = sqlite3PExpr(pParse, (int)(138), null, null); sqlite3PExprAddSelect(pParse, yymsp[-2].minor.yy528, yymsp[-1].minor.yy47); }
			break;  case  220 :  { yymsp[-4].minor.yy528 = sqlite3PExpr(pParse, (int)(49), yymsp[-4].minor.yy528, null); sqlite3PExprAddSelect(pParse, yymsp[-4].minor.yy528, yymsp[-1].minor.yy47); if ((yymsp[-3].minor.yy394) != 0) yymsp[-4].minor.yy528 = sqlite3PExpr(pParse, (int)(19), yymsp[-4].minor.yy528, null); }
			break;  case  221 :  { SrcList pSrc = sqlite3SrcListAppend(pParse, null, &yymsp[-2].minor.yy0, &yymsp[-1].minor.yy0); Select pSelect = sqlite3SelectNew(pParse, null, pSrc, null, null, null, null, (uint)(0), null); if ((yymsp[0].minor.yy322) != null) sqlite3SrcListFuncArgs(pParse, pSelect ? pSrc : null, yymsp[0].minor.yy322); yymsp[-4].minor.yy528 = sqlite3PExpr(pParse, (int)(49), yymsp[-4].minor.yy528, null); sqlite3PExprAddSelect(pParse, yymsp[-4].minor.yy528, pSelect); if ((yymsp[-3].minor.yy394) != 0) yymsp[-4].minor.yy528 = sqlite3PExpr(pParse, (int)(19), yymsp[-4].minor.yy528, null); }
			break;  case  222 :  { Expr p; p = yymsp[-3].minor.yy528 = sqlite3PExpr(pParse, (int)(20), null, null); sqlite3PExprAddSelect(pParse, p, yymsp[-1].minor.yy47); }
			break;  case  223 :  { yymsp[-4].minor.yy528 = sqlite3PExpr(pParse, (int)(157), yymsp[-3].minor.yy528, null); if ((yymsp[-4].minor.yy528) != null) { yymsp[-4].minor.yy528.x.pList = yymsp[-1].minor.yy528 ? sqlite3ExprListAppend(pParse, yymsp[-2].minor.yy322, yymsp[-1].minor.yy528) : yymsp[-2].minor.yy322; sqlite3ExprSetHeightAndFlags(pParse, yymsp[-4].minor.yy528); } else { sqlite3ExprListDelete(pParse.db, yymsp[-2].minor.yy322); sqlite3ExprDelete(pParse.db, yymsp[-1].minor.yy528); } }
			break;  case  224 :  { yymsp[-4].minor.yy322 = sqlite3ExprListAppend(pParse, yymsp[-4].minor.yy322, yymsp[-2].minor.yy528); yymsp[-4].minor.yy322 = sqlite3ExprListAppend(pParse, yymsp[-4].minor.yy322, yymsp[0].minor.yy528); }
			break;  case  225 :  { yymsp[-3].minor.yy322 = sqlite3ExprListAppend(pParse, null, yymsp[-2].minor.yy528); yymsp[-3].minor.yy322 = sqlite3ExprListAppend(pParse, yymsp[-3].minor.yy322, yymsp[0].minor.yy528); }
			break;  case  228 :  { yymsp[0].minor.yy528 = yymsp[0].minor.yy528; }
			break;  case  231 :  { yymsp[-2].minor.yy322 = sqlite3ExprListAppend(pParse, yymsp[-2].minor.yy322, yymsp[0].minor.yy528); }
			break;  case  232 :  { yymsp[0].minor.yy322 = sqlite3ExprListAppend(pParse, null, yymsp[0].minor.yy528); }
			break;  case  234 :  case  239 :  ;
			{ yymsp[-2].minor.yy322 = yymsp[-1].minor.yy322; }
			break;  case  235 :  { sqlite3CreateIndex(pParse, &yymsp[-7].minor.yy0, &yymsp[-6].minor.yy0, sqlite3SrcListAppend(pParse, null, &yymsp[-4].minor.yy0, null), yymsp[-2].minor.yy322, (int)(yymsp[-10].minor.yy394), &yymsp[-11].minor.yy0, yymsp[0].minor.yy528, (int)(0), (int)(yymsp[-8].minor.yy394), (byte)(0)); if (((pParse.eParseMode) >= (2)) && ((pParse.pNewIndex) != null)) { sqlite3RenameTokenMap(pParse, pParse.pNewIndex.zName, &yymsp[-4].minor.yy0); } }
			break;  case  236 :  case  278 :  ;
			{ yymsp[0].minor.yy394 = (int)(2); }
			break;  case  237 :  { yymsp[1].minor.yy394 = (int)(0); }
			break;  case  240 :  { yymsp[-4].minor.yy322 = parserAddExprIdListTerm(pParse, yymsp[-4].minor.yy322, &yymsp[-2].minor.yy0, (int)(yymsp[-1].minor.yy394), (int)(yymsp[0].minor.yy394)); }
			break;  case  241 :  { yymsp[-2].minor.yy322 = parserAddExprIdListTerm(pParse, null, &yymsp[-2].minor.yy0, (int)(yymsp[-1].minor.yy394), (int)(yymsp[0].minor.yy394)); }
			break;  case  244 :  { sqlite3DropIndex(pParse, yymsp[0].minor.yy131, (int)(yymsp[-1].minor.yy394)); }
			break;  case  245 :  { sqlite3Vacuum(pParse, null, yymsp[0].minor.yy528); }
			break;  case  246 :  { sqlite3Vacuum(pParse, &yymsp[-1].minor.yy0, yymsp[0].minor.yy528); }
			break;  case  249 :  { sqlite3Pragma(pParse, &yymsp[-1].minor.yy0, &yymsp[0].minor.yy0, null, (int)(0)); }
			break;  case  250 :  { sqlite3Pragma(pParse, &yymsp[-3].minor.yy0, &yymsp[-2].minor.yy0, &yymsp[0].minor.yy0, (int)(0)); }
			break;  case  251 :  { sqlite3Pragma(pParse, &yymsp[-4].minor.yy0, &yymsp[-3].minor.yy0, &yymsp[-1].minor.yy0, (int)(0)); }
			break;  case  252 :  { sqlite3Pragma(pParse, &yymsp[-3].minor.yy0, &yymsp[-2].minor.yy0, &yymsp[0].minor.yy0, (int)(1)); }
			break;  case  253 :  { sqlite3Pragma(pParse, &yymsp[-4].minor.yy0, &yymsp[-3].minor.yy0, &yymsp[-1].minor.yy0, (int)(1)); }
			break;  case  256 :  { Token all = new Token(); all.z = yymsp[-3].minor.yy0.z; all.n = (uint)((int)(yymsp[0].minor.yy0.z - yymsp[-3].minor.yy0.z) + yymsp[0].minor.yy0.n); sqlite3FinishTrigger(pParse, yymsp[-1].minor.yy33, &all); }
			break;  case  257 :  { sqlite3BeginTrigger(pParse, &yymsp[-7].minor.yy0, &yymsp[-6].minor.yy0, (int)(yymsp[-5].minor.yy394), (int)(yymsp[-4].minor.yy180.a), yymsp[-4].minor.yy180.b, yymsp[-2].minor.yy131, yymsp[0].minor.yy528, (int)(yymsp[-10].minor.yy394), (int)(yymsp[-8].minor.yy394)); yymsp[-10].minor.yy0 = (Token)((yymsp[-6].minor.yy0.n) == (0) ? yymsp[-7].minor.yy0 : yymsp[-6].minor.yy0); }
			break;  case  258 :  { yymsp[0].minor.yy394 = (int)(yymsp[0].major); }
			break;  case  259 :  { yymsp[-1].minor.yy394 = (int)(65); }
			break;  case  260 :  { yymsp[1].minor.yy394 = (int)(33); }
			break;  case  261 :  case  262 :  ;
			{ yymsp[0].minor.yy180.a = (int)(yymsp[0].major); yymsp[0].minor.yy180.b = null; }
			break;  case  263 :  { yymsp[-2].minor.yy180.a = (int)(129); yymsp[-2].minor.yy180.b = yymsp[0].minor.yy254; }
			break;  case  264 :  case  283 :  ;
			{ yymsp[1].minor.yy528 = null; }
			break;  case  265 :  case  284 :  ;
			{ yymsp[-1].minor.yy528 = yymsp[0].minor.yy528; }
			break;  case  266 :  { yymsp[-2].minor.yy33.pLast.pNext = yymsp[-1].minor.yy33; yymsp[-2].minor.yy33.pLast = yymsp[-1].minor.yy33; }
			break;  case  267 :  { yymsp[-1].minor.yy33.pLast = yymsp[-1].minor.yy33; }
			break;  case  268 :  { yymsp[-2].minor.yy0 = (Token)(yymsp[0].minor.yy0); sqlite3ErrorMsg(pParse, "qualified table names are not allowed on INSERT, UPDATE, and DELETE statements within triggers"); }
			break;  case  269 :  { sqlite3ErrorMsg(pParse, "the INDEXED BY clause is not allowed on UPDATE or DELETE statements within triggers"); }
			break;  case  270 :  { sqlite3ErrorMsg(pParse, "the NOT INDEXED clause is not allowed on UPDATE or DELETE statements within triggers"); }
			break;  case  271 :  { yylhsminor.yy33 = sqlite3TriggerUpdateStep(pParse, &yymsp[-6].minor.yy0, yymsp[-2].minor.yy131, yymsp[-3].minor.yy322, yymsp[-1].minor.yy528, (byte)(yymsp[-7].minor.yy394), yymsp[-8].minor.yy0.z, yymsp[0].minor.yy522); }
			yymsp[-8].minor.yy33 = yylhsminor.yy33; break;  case  272 :  { yylhsminor.yy33 = sqlite3TriggerInsertStep(pParse, &yymsp[-4].minor.yy0, yymsp[-3].minor.yy254, yymsp[-2].minor.yy47, (byte)(yymsp[-6].minor.yy394), yymsp[-1].minor.yy444, yymsp[-7].minor.yy522, yymsp[0].minor.yy522); }
			yymsp[-7].minor.yy33 = yylhsminor.yy33; break;  case  273 :  { yylhsminor.yy33 = sqlite3TriggerDeleteStep(pParse, &yymsp[-3].minor.yy0, yymsp[-1].minor.yy528, yymsp[-5].minor.yy0.z, yymsp[0].minor.yy522); }
			yymsp[-5].minor.yy33 = yylhsminor.yy33; break;  case  274 :  { yylhsminor.yy33 = sqlite3TriggerSelectStep(pParse.db, yymsp[-1].minor.yy47, yymsp[-2].minor.yy522, yymsp[0].minor.yy522); }
			yymsp[-2].minor.yy33 = yylhsminor.yy33; break;  case  275 :  { yymsp[-3].minor.yy528 = sqlite3PExpr(pParse, (int)(71), null, null); if ((yymsp[-3].minor.yy528) != null) { yymsp[-3].minor.yy528.affExpr = (sbyte)(4); } }
			break;  case  276 :  { yymsp[-5].minor.yy528 = sqlite3ExprAlloc(pParse.db, (int)(71), &yymsp[-1].minor.yy0, (int)(1)); if ((yymsp[-5].minor.yy528) != null) { yymsp[-5].minor.yy528.affExpr = ((sbyte)(yymsp[-3].minor.yy394)); } }
			break;  case  277 :  { yymsp[0].minor.yy394 = (int)(1); }
			break;  case  279 :  { yymsp[0].minor.yy394 = (int)(3); }
			break;  case  280 :  { sqlite3DropTrigger(pParse, yymsp[0].minor.yy131, (int)(yymsp[-1].minor.yy394)); }
			break;  case  281 :  { sqlite3Attach(pParse, yymsp[-3].minor.yy528, yymsp[-1].minor.yy528, yymsp[0].minor.yy528); }
			break;  case  282 :  { sqlite3Detach(pParse, yymsp[0].minor.yy528); }
			break;  case  285 :  { sqlite3Reindex(pParse, null, null); }
			break;  case  286 :  { sqlite3Reindex(pParse, &yymsp[-1].minor.yy0, &yymsp[0].minor.yy0); }
			break;  case  287 :  { sqlite3Analyze(pParse, null, null); }
			break;  case  288 :  { sqlite3Analyze(pParse, &yymsp[-1].minor.yy0, &yymsp[0].minor.yy0); }
			break;  case  289 :  { sqlite3AlterRenameTable(pParse, yymsp[-3].minor.yy131, &yymsp[0].minor.yy0); }
			break;  case  290 :  { yymsp[-1].minor.yy0.n = (uint)((int)(pParse.sLastToken.z - yymsp[-1].minor.yy0.z) + pParse.sLastToken.n); sqlite3AlterFinishAddColumn(pParse, &yymsp[-1].minor.yy0); }
			break;  case  291 :  { sqlite3AlterDropColumn(pParse, yymsp[-3].minor.yy131, &yymsp[0].minor.yy0); }
			break;  case  292 :  { disableLookaside(pParse); sqlite3AlterBeginAddColumn(pParse, yymsp[0].minor.yy131); }
			break;  case  293 :  { sqlite3AlterRenameColumn(pParse, yymsp[-5].minor.yy131, &yymsp[-2].minor.yy0, &yymsp[0].minor.yy0); }
			break;  case  294 :  { sqlite3VtabFinishParse(pParse, null); }
			break;  case  295 :  { sqlite3VtabFinishParse(pParse, &yymsp[0].minor.yy0); }
			break;  case  296 :  { sqlite3VtabBeginParse(pParse, &yymsp[-3].minor.yy0, &yymsp[-2].minor.yy0, &yymsp[0].minor.yy0, (int)(yymsp[-4].minor.yy394)); }
			break;  case  297 :  { sqlite3VtabArgInit(pParse); }
			break;  case  298 :  case  299 :  ;  case  300 :  ;
			{ sqlite3VtabArgExtend(pParse, &yymsp[0].minor.yy0); }
			break;  case  301 :  case  302 :  ;
			{ sqlite3WithPush(pParse, yymsp[0].minor.yy521, (byte)(1)); }
			break;  case  303 :  { yymsp[0].minor.yy516 = (byte)(1); }
			break;  case  304 :  { yymsp[-1].minor.yy516 = (byte)(0); }
			break;  case  305 :  { yymsp[-2].minor.yy516 = (byte)(2); }
			break;  case  306 :  { yymsp[-5].minor.yy385 = sqlite3CteNew(pParse, &yymsp[-5].minor.yy0, yymsp[-4].minor.yy322, yymsp[-1].minor.yy47, (byte)(yymsp[-3].minor.yy516)); }
			break;  case  307 :  { yymsp[0].minor.yy521 = sqlite3WithAdd(pParse, null, yymsp[0].minor.yy385); }
			break;  case  308 :  { yymsp[-2].minor.yy521 = sqlite3WithAdd(pParse, yymsp[-2].minor.yy521, yymsp[0].minor.yy385); }
			break;  case  309 :  { yylhsminor.yy41 = yymsp[0].minor.yy41; }
			yymsp[0].minor.yy41 = yylhsminor.yy41; break;  case  310 :  { sqlite3WindowChain(pParse, yymsp[0].minor.yy41, yymsp[-2].minor.yy41); yymsp[0].minor.yy41.pNextWin = yymsp[-2].minor.yy41; yylhsminor.yy41 = yymsp[0].minor.yy41; }
			yymsp[-2].minor.yy41 = yylhsminor.yy41; break;  case  311 :  { if ((yymsp[-1].minor.yy41) != null) { yymsp[-1].minor.yy41.zName = sqlite3DbStrNDup(pParse.db, yymsp[-4].minor.yy0.z, (ulong)(yymsp[-4].minor.yy0.n)); } yylhsminor.yy41 = yymsp[-1].minor.yy41; }
			yymsp[-4].minor.yy41 = yylhsminor.yy41; break;  case  312 :  { yymsp[-4].minor.yy41 = sqlite3WindowAssemble(pParse, yymsp[0].minor.yy41, yymsp[-2].minor.yy322, yymsp[-1].minor.yy322, null); }
			break;  case  313 :  { yylhsminor.yy41 = sqlite3WindowAssemble(pParse, yymsp[0].minor.yy41, yymsp[-2].minor.yy322, yymsp[-1].minor.yy322, &yymsp[-5].minor.yy0); }
			yymsp[-5].minor.yy41 = yylhsminor.yy41; break;  case  314 :  { yymsp[-3].minor.yy41 = sqlite3WindowAssemble(pParse, yymsp[0].minor.yy41, null, yymsp[-1].minor.yy322, null); }
			break;  case  315 :  { yylhsminor.yy41 = sqlite3WindowAssemble(pParse, yymsp[0].minor.yy41, null, yymsp[-1].minor.yy322, &yymsp[-4].minor.yy0); }
			yymsp[-4].minor.yy41 = yylhsminor.yy41; break;  case  316 :  case  335 :  ;
			{ yylhsminor.yy41 = yymsp[0].minor.yy41; }
			yymsp[0].minor.yy41 = yylhsminor.yy41; break;  case  317 :  { yylhsminor.yy41 = sqlite3WindowAssemble(pParse, yymsp[0].minor.yy41, null, null, &yymsp[-1].minor.yy0); }
			yymsp[-1].minor.yy41 = yylhsminor.yy41; break;  case  318 :  { yymsp[1].minor.yy41 = sqlite3WindowAlloc(pParse, (int)(0), (int)(90), null, (int)(85), null, (byte)(0)); }
			break;  case  319 :  { yylhsminor.yy41 = sqlite3WindowAlloc(pParse, (int)(yymsp[-2].minor.yy394), (int)(yymsp[-1].minor.yy595.eType), yymsp[-1].minor.yy595.pExpr, (int)(85), null, (byte)(yymsp[0].minor.yy516)); }
			yymsp[-2].minor.yy41 = yylhsminor.yy41; break;  case  320 :  { yylhsminor.yy41 = sqlite3WindowAlloc(pParse, (int)(yymsp[-5].minor.yy394), (int)(yymsp[-3].minor.yy595.eType), yymsp[-3].minor.yy595.pExpr, (int)(yymsp[-1].minor.yy595.eType), yymsp[-1].minor.yy595.pExpr, (byte)(yymsp[0].minor.yy516)); }
			yymsp[-5].minor.yy41 = yylhsminor.yy41; break;  case  322 :  case  324 :  ;
			{ yylhsminor.yy595 = (FrameBound)(yymsp[0].minor.yy595); }
			yymsp[0].minor.yy595 = (FrameBound)(yylhsminor.yy595); break;  case  323 :  case  325 :  ;  case  327 :  ;
			{ yylhsminor.yy595.eType = (int)(yymsp[-1].major); yylhsminor.yy595.pExpr = null; }
			yymsp[-1].minor.yy595 = (FrameBound)(yylhsminor.yy595); break;  case  326 :  { yylhsminor.yy595.eType = (int)(yymsp[0].major); yylhsminor.yy595.pExpr = yymsp[-1].minor.yy528; }
			yymsp[-1].minor.yy595 = (FrameBound)(yylhsminor.yy595); break;  case  328 :  { yymsp[1].minor.yy516 = (byte)(0); }
			break;  case  329 :  { yymsp[-1].minor.yy516 = (byte)(yymsp[0].minor.yy516); }
			break;  case  330 :  case  331 :  ;
			{ yymsp[-1].minor.yy516 = (byte)(yymsp[-1].major); }
			break;  case  332 :  { yymsp[0].minor.yy516 = (byte)(yymsp[0].major); }
			break;  case  333 :  { yymsp[-1].minor.yy41 = yymsp[0].minor.yy41; }
			break;  case  334 :  { if ((yymsp[0].minor.yy41) != null) { yymsp[0].minor.yy41.pFilter = yymsp[-1].minor.yy528; } else { sqlite3ExprDelete(pParse.db, yymsp[-1].minor.yy528); } yylhsminor.yy41 = yymsp[0].minor.yy41; }
			yymsp[-1].minor.yy41 = yylhsminor.yy41; break;  case  336 :  { yylhsminor.yy41 = (Window)(sqlite3DbMallocZero(pParse.db, (ulong)(sizeof(Window)))); if ((yylhsminor.yy41) != null) { yylhsminor.yy41.eFrmType = (byte)(166); yylhsminor.yy41.pFilter = yymsp[0].minor.yy528; } else { sqlite3ExprDelete(pParse.db, yymsp[0].minor.yy528); } }
			yymsp[0].minor.yy41 = yylhsminor.yy41; break;  case  337 :  { yymsp[-3].minor.yy41 = yymsp[-1].minor.yy41; }
			break;  case  338 :  { yymsp[-1].minor.yy41 = (Window)(sqlite3DbMallocZero(pParse.db, (ulong)(sizeof(Window)))); if ((yymsp[-1].minor.yy41) != null) { yymsp[-1].minor.yy41.zName = sqlite3DbStrNDup(pParse.db, yymsp[0].minor.yy0.z, (ulong)(yymsp[0].minor.yy0.n)); } }
			break;  case  339 :  { yymsp[-4].minor.yy528 = yymsp[-1].minor.yy528; }
			break;
			default :  ; break;
		}

		yygoto = (int) (yyRuleInfoLhs[yyruleno]);
    yysize = (int) (yyRuleInfoNRhs[yyruleno]);
    yyact = (ushort) (yy_find_reduce_action((ushort)(yymsp[yysize].stateno), (ushort) (yygoto)));
    yymsp += yysize + 1;
    yypParser.yytos = yymsp;
    yymsp->stateno = (ushort) (yyact);
    yymsp->major = ((ushort)(yygoto));
    return (ushort) (yyact);
}
	public static void yy_shift(yyParser yypParser, ushort yyNewState, ushort yyMajor, Token yyMinor)
	{
		yyStackEntry* yytos;
		yypParser.yytos++;
		if ((yypParser.yytos) > (yypParser.yystackEnd))
		{
			yypParser.yytos--;
			yyStackOverflow(yypParser);
			return;
		}

		if ((yyNewState) > (573))
		{
			yyNewState += (ushort)(1236 - 831);
		}

		yytos = yypParser.yytos;
		yytos->stateno = (ushort)(yyNewState);
		yytos->major = (ushort)(yyMajor);
		yytos->minor.yy0 = (Token)(yyMinor);
	}
	public static void yy_syntax_error(yyParser yypParser, int yymajor, Token yyminor)
	{
		Parse pParse = yypParser.pParse;
		if ((yyminor.z[0]) != 0)
		{
			sqlite3ErrorMsg(pParse, "near \"%T\": syntax error", &yyminor);
		}
		else
		{
			sqlite3ErrorMsg(pParse, "incomplete input");
		}

		yypParser.pParse = pParse;
	}
	public static void yyStackOverflow(yyParser yypParser)
	{
		Parse pParse = yypParser.pParse;
		while ((yypParser.yytos) > (yypParser.yystack))
		{
			yy_pop_parser_stack(yypParser);
		}

		sqlite3ErrorMsg(pParse, "parser stack overflow");
		yypParser.pParse = pParse;
	}
}
}