// Generated by Hebron at 4/3/2022 2:10:11 AM

using System;
using System.Runtime.InteropServices;
using Hebron.Runtime;

namespace SqliteSharp
{
	unsafe partial class Sqlite
	{
		public static void pragmaVtabCursorClear(PragmaVtabCursor pCsr)
		{
			int i = 0;
			sqlite3_finalize(pCsr.pPragma);
			pCsr.pPragma = null;
			for (i = (int)(0); (i) < ((int)(2 * sizeof(sbyte) / sizeof(sbyte*))); i++)
			{
				sqlite3_free(pCsr.azArg[i]);
				pCsr.azArg[i] = null;
			}
		}
	}
}