// Generated by Hebron at 4/3/2022 2:10:11 AM

using System;
using System.Runtime.InteropServices;
using Hebron.Runtime;

namespace SqliteSharp
{
	unsafe partial class Sqlite
	{
		public static int memdbEnlarge(MemStore* p, long newSz)
		{
			byte* pNew;
			if (((p->mFlags & 2) == (0)) || ((p->nMmap) > (0)))
			{
				return (int)(13);
			}

			if ((newSz) > (p->szMax))
			{
				return (int)(13);
			}

			newSz *= (long)(2);
			if ((newSz) > (p->szMax))
				newSz = (long)(p->szMax);
			pNew = sqlite3Realloc(p->aData, (ulong)(newSz));
			if ((pNew) == (null))
				return (int)(10 | (12 << 8));
			p->aData = pNew;
			p->szAlloc = (long)(newSz);
			return (int)(0);
		}
		public static void memdbEnter(MemStore* p)
		{
			sqlite3_mutex_enter(p->pMutex);
		}
		public static void memdbLeave(MemStore* p)
		{
			sqlite3_mutex_leave(p->pMutex);
		}
	}
}