// Generated by Hebron at 4/3/2022 2:10:11 AM

using System;
using System.Runtime.InteropServices;
using Hebron.Runtime;

namespace SqliteSharp
{
	unsafe partial class Sqlite
	{
		public static double getDoubleArg(PrintfArguments p)
		{
			if ((p.nArg) <= (p.nUsed))
				return (double)(0.0);
			return (double)(sqlite3_value_double(p.apArg[p.nUsed++]));
		}
		public static long getIntArg(PrintfArguments p)
		{
			if ((p.nArg) <= (p.nUsed))
				return (long)(0);
			return (long)(sqlite3_value_int64(p.apArg[p.nUsed++]));
		}
	}
}