// Generated by Hebron at 4/3/2022 2:10:11 AM

using System;
using System.Runtime.InteropServices;
using Hebron.Runtime;

namespace SqliteSharp
{
	unsafe partial class Sqlite
	{
		public static void preserveExpr(IdxExprTrans pTrans, Expr pExpr)
		{
			WhereExprMod pNew;
			pNew = sqlite3DbMallocRaw(pTrans.db, (ulong)(sizeof(WhereExprMod)));
			if ((pNew) == (null))
				return;
			pNew.pNext = pTrans.pWInfo.pExprMods;
			pTrans.pWInfo.pExprMods = pNew;
			pNew.pExpr = pExpr;
			CRuntime.memcpy(pNew.orig, pExpr, (ulong)(sizeof(Expr)));
		}
	}
}