// Generated by Hebron at 4/3/2022 2:10:11 AM

using System;
using System.Runtime.InteropServices;
using Hebron.Runtime;

namespace SqliteSharp
{
	unsafe partial class Sqlite
	{
		public static int sqlite3InvokeBusyHandler(BusyHandler p)
		{
			int rc = 0;
			if (((p.xBusyHandler) == (null)) || ((p.nBusy) < (0)))
				return (int)(0);
			rc = (int)(p.xBusyHandler(p.pBusyArg, (int)(p.nBusy)));
			if ((rc) == (0))
			{
				p.nBusy = (int)(-1);
			}
			else
			{
				p.nBusy++;
			}

			return (int)(rc);
		}
	}
}