// Generated by Hebron at 4/3/2022 2:10:11 AM

using System;
using System.Runtime.InteropServices;
using Hebron.Runtime;

namespace SqliteSharp
{
	unsafe partial class Sqlite
	{
		public static void disableTerm(WhereLevel pLevel, WhereTerm pTerm)
		{
			int nLoop = (int)(0);
			while ((((pTerm.wtFlags & 0x0004) == (0)) && (((pLevel.iLeftJoin) == (0)) || (((pTerm.pExpr).flags & (0x000001)) != 0))) && ((pLevel.notReady & pTerm.prereqAll) == (0)))
			{
				if (((nLoop) != 0) && ((pTerm.wtFlags & 0x0400) != 0))
				{
					pTerm.wtFlags |= (ushort)(0x0200);
				}
				else
				{
					pTerm.wtFlags |= (ushort)(0x0004);
				}

				if ((pTerm.iParent) < (0))
					break;
				pTerm = pTerm.pWC.a[pTerm.iParent];
				pTerm.nChild--;
				if (pTerm.nChild != 0)
					break;
				nLoop++;
			}
		}
	}
}