// Generated by Hebron at 4/3/2022 2:10:11 AM

using System;
using System.Runtime.InteropServices;
using Hebron.Runtime;

namespace SqliteSharp
{
	unsafe partial class Sqlite
	{
		public static int checkColumnOverlap(IdList* pIdList, ExprList pEList)
		{
			int e = 0;
			if (((pIdList) == (null)) || ((pEList) == (null)))
				return (int)(1);
			for (e = (int)(0); (e) < (pEList.nExpr); e++)
			{
				if ((sqlite3IdListIndex(pIdList, pEList.a[e].zEName)) >= (0))
					return (int)(1);
			}

			return (int)(0);
		}
		public static int nameInUsingClause(IdList* pUsing, sbyte* zCol)
		{
			if ((pUsing) != null)
			{
				int k = 0;
				for (k = (int)(0); (k) < (pUsing->nId); k++)
				{
					if ((sqlite3StrICmp(pUsing->a[k].zName, zCol)) == (0))
						return (int)(1);
				}
			}

			return (int)(0);
		}
		public static int sqlite3IdListIndex(IdList* pList, sbyte* zName)
		{
			int i = 0;
			if ((pList) == (null))
				return (int)(-1);
			for (i = (int)(0); (i) < (pList->nId); i++)
			{
				if ((sqlite3StrICmp(pList->a[i].zName, zName)) == (0))
					return (int)(i);
			}

			return (int)(-1);
		}
	}
}