// Generated by Hebron at 4/3/2022 2:10:11 AM

using System;
using System.Runtime.InteropServices;
using Hebron.Runtime;

namespace SqliteSharp
{
	unsafe partial class Sqlite
	{
		public static int sqlite3UpsertNextIsIPK(Upsert pUpsert)
		{
			Upsert pNext;
			if (((pUpsert) == (null)))
				return (int)(0);
			pNext = pUpsert.pNextUpsert;
			if ((pNext) == (null))
				return (int)(1);
			if ((pNext.pUpsertTarget) == (null))
				return (int)(1);
			if ((pNext.pUpsertIdx) == (null))
				return (int)(1);
			return (int)(0);
		}
		public static Upsert sqlite3UpsertOfIndex(Upsert pUpsert, Index pIdx)
		{
			while ((((pUpsert) != null) && (pUpsert.pUpsertTarget != null)) && (pUpsert.pUpsertIdx != pIdx))
			{
				pUpsert = pUpsert.pNextUpsert;
			}

			return pUpsert;
		}
	}
}