// Generated by Hebron at 4/3/2022 2:10:11 AM

using System;
using System.Runtime.InteropServices;
using Hebron.Runtime;

namespace SqliteSharp
{
	unsafe partial class Sqlite
	{
		public static int sqlite3MatchEName(ExprList_item* pItem, sbyte* zCol, sbyte* zTab, sbyte* zDb)
		{
			int n = 0;
			sbyte* zSpan;
			if (pItem->eEName != 2)
				return (int)(0);
			zSpan = pItem->zEName;
			for (n = (int)(0); ((zSpan[n]) != 0) && (zSpan[n] != 46); n++)
			{
			}

			if (((zDb) != null) && ((sqlite3_strnicmp(zSpan, zDb, (int)(n)) != 0) || (zDb[n] != 0)))
			{
				return (int)(0);
			}

			zSpan += n + 1;
			for (n = (int)(0); ((zSpan[n]) != 0) && (zSpan[n] != 46); n++)
			{
			}

			if (((zTab) != null) && ((sqlite3_strnicmp(zSpan, zTab, (int)(n)) != 0) || (zTab[n] != 0)))
			{
				return (int)(0);
			}

			zSpan += n + 1;
			if (((zCol) != null) && (sqlite3StrICmp(zSpan, zCol) != 0))
			{
				return (int)(0);
			}

			return (int)(1);
		}
	}
}