// Generated by Hebron at 4/3/2022 2:10:11 AM

using System;
using System.Runtime.InteropServices;
using Hebron.Runtime;

namespace SqliteSharp
{
	unsafe partial class Sqlite
	{
		public static void sqlite3DequoteToken(Token* p)
		{
			uint i = 0;
			if ((p->n) < (2))
				return;
			if ((sqlite3CtypeMap[(byte)(p->z[0])] & 0x80) == 0)
				return;
			for (i = (uint)(1); (i) < (p->n - 1); i++)
			{
				if ((sqlite3CtypeMap[(byte)(p->z[i])] & 0x80) != 0)
					return;
			}

			p->n -= (uint)(2);
			p->z++;
		}
		public static void sqlite3TokenInit(Token* p, sbyte* z)
		{
			p->z = z;
			p->n = (uint)(sqlite3Strlen30(z));
		}
	}
}