// Generated by Hebron at 4/3/2022 2:10:11 AM

using System;
using System.Runtime.InteropServices;
using Hebron.Runtime;

namespace SqliteSharp
{
	unsafe partial class Sqlite
	{
		public static void sqlite3SelectDestInit(SelectDest pDest, int eDest, int iParm)
		{
			pDest.eDest = ((byte)(eDest));
			pDest.iSDParm = (int)(iParm);
			pDest.iSDParm2 = (int)(0);
			pDest.zAffSdst = null;
			pDest.iSdst = (int)(0);
			pDest.nSdst = (int)(0);
		}
	}
}